insert into emozioni (nome, descrizione, colore_assoc, colore_hex, icona)
values
  ('Ammirazione', 'Stima intensa verso una persona, un gesto o una qualita'' percepita come superiore o degna di rispetto.', 'Oro', '#c9a227', '👏'),
  ('Amore', 'Coinvolgimento affettivo profondo, legato a cura, attaccamento, desiderio di vicinanza e protezione.', 'Rosa', '#e84393', '❤️'),
  ('Ansia', 'Stato di tensione anticipatoria, spesso legato a incertezza, attesa o timore di conseguenze future.', 'Viola', '#8e44ad', '😟'),
  ('Calma', 'Condizione di quiete emotiva, autocontrollo e assenza di agitazione evidente.', 'Azzurro', '#74b9ff', '😌'),
  ('Compassione', 'Partecipazione alla sofferenza altrui, accompagnata dal desiderio di aiutare o proteggere.', 'Rosa tenue', '#fd79a8', '🤲'),
  ('Confusione', 'Disorientamento cognitivo o emotivo, spesso davanti a informazioni contraddittorie o situazioni ambigue.', 'Grigio', '#95a5a6', '😕'),
  ('Curiosità', 'Interesse attivo verso qualcosa di sconosciuto, misterioso o non ancora compreso.', 'Turchese', '#00cec9', '🧐'),
  ('Delusione', 'Senso di amarezza quando un''aspettativa, una promessa o una fiducia viene disattesa.', 'Blu grigio', '#607d8b', '😞'),
  ('Desiderio', 'Attrazione o tensione verso una persona, un oggetto, un esito o una condizione immaginata come appagante.', 'Magenta', '#d63031', '✨'),
  ('Determinazione', 'Volonta'' ferma di perseguire un obiettivo nonostante ostacoli, dubbi o pressioni esterne.', 'Rosso scuro', '#b33939', '💪'),
  ('Disgusto', 'Reazione di repulsione verso qualcosa percepito come contaminante, moralmente inaccettabile o fisicamente sgradevole.', 'Verde acido', '#6ab04c', '🤢'),
  ('Disprezzo', 'Svalutazione ostile di qualcuno o qualcosa, con senso di superiorita'' o rifiuto morale.', 'Grigio scuro', '#636e72', '🙄'),
  ('Entusiasmo', 'Energia positiva e partecipazione vivace, spesso associata a aspettativa, scoperta o successo imminente.', 'Arancione', '#f39c12', '🤩'),
  ('Felicità', 'Gioia e soddisfazione, spesso associate a momenti positivi, riuscita o relazioni armoniose.', 'Verde', '#27ae60', '😁'),
  ('Fiducia', 'Sicurezza verso una persona, una relazione, una scelta o lo sviluppo di una situazione.', 'Blu', '#0984e3', '🤝'),
  ('Frustrazione', 'Tensione irritata prodotta da un ostacolo, un limite o un fallimento ripetuto.', 'Arancione scuro', '#e17055', '😤'),
  ('Gelosia', 'Paura o dolore di perdere un legame affettivo a favore di qualcun altro.', 'Verde scuro', '#218c74', '😒'),
  ('Gratitudine', 'Riconoscenza verso qualcuno o qualcosa percepito come dono, aiuto o beneficio ricevuto.', 'Verde chiaro', '#55efc4', '🙏'),
  ('Imbarazzo', 'Disagio sociale lieve o medio, spesso legato all''essere osservati, esposti o fuori posto.', 'Rosa pallido', '#fab1a0', '😳'),
  ('Invidia', 'Dolore o irritazione davanti a un vantaggio, qualita'' o possesso attribuito ad altri.', 'Verde oliva', '#839c49', '😣'),
  ('Interesse', 'Attenzione coinvolta e orientata verso un tema, una persona o un evento significativo.', 'Ciano', '#00a8cc', '👀'),
  ('Nostalgia', 'Dolcezza malinconica verso persone, luoghi o tempi passati percepiti come perduti o lontani.', 'Lavanda', '#a29bfe', '🌙'),
  ('Orgoglio', 'Soddisfazione per il proprio valore, risultato o appartenenza, positiva o talvolta eccessiva.', 'Porpora', '#9b59b6', '😌'),
  ('Paura', 'Timore davanti a una minaccia, un rischio o una situazione percepita come pericolosa.', 'Nero', '#2c3e50', '😨'),
  ('Preoccupazione', 'Pensiero insistente su un problema possibile o reale, con tensione moderata e attenzione al rischio.', 'Blu scuro', '#34495e', '😧'),
  ('Rabbia', 'Irritazione intensa o ostilita'', spesso provocata da ingiustizia, offesa, frustrazione o conflitto.', 'Rosso', '#c0392b', '😡'),
  ('Rassegnazione', 'Accettazione amara o stanca di una situazione percepita come inevitabile o non modificabile.', 'Grigio blu', '#718093', '😔'),
  ('Rimorso', 'Dolore morale per una propria azione o omissione percepita come sbagliata.', 'Indaco', '#4834d4', '😖'),
  ('Rispetto', 'Riconoscimento del valore, del ruolo o dei limiti di un''altra persona.', 'Blu reale', '#1e3799', '🙇'),
  ('Senso di colpa', 'Responsabilita'' dolorosa per aver causato, permesso o immaginato un danno.', 'Marrone', '#8e5a3c', '😓'),
  ('Serenità', 'Benessere quieto e stabile, meno euforico della felicita'' e piu'' vicino all''equilibrio.', 'Verde acqua', '#00b894', '🙂'),
  ('Sollievo', 'Allentamento della tensione dopo un pericolo evitato, una conferma ricevuta o una paura dissipata.', 'Celeste', '#81ecec', '😮‍💨'),
  ('Solitudine', 'Percezione dolorosa di isolamento, distanza dagli altri o mancanza di riconoscimento affettivo.', 'Blu notte', '#273c75', '🫥'),
  ('Sorpresa', 'Reazione improvvisa davanti a un evento inatteso, positiva, negativa o neutra.', 'Giallo', '#f1c40f', '😮'),
  ('Sospetto', 'Diffidenza verso intenzioni, parole o comportamenti percepiti come poco chiari o potenzialmente minacciosi.', 'Viola scuro', '#6c5ce7', '🤨'),
  ('Speranza', 'Attesa fiduciosa che un esito desiderato sia possibile nonostante incertezza o difficolta''.', 'Verde smeraldo', '#2ecc71', '🌱'),
  ('Tenerezza', 'Affetto delicato e protettivo verso qualcuno percepito come caro, fragile o commovente.', 'Pesca', '#ffbe76', '🥺'),
  ('Tristezza', 'Malinconia, dolore o perdita, spesso associati a separazione, fallimento o vulnerabilita''.', 'Blu', '#3498db', '😭'),
  ('Vergogna', 'Dolore legato all''immagine di se'', alla paura del giudizio o alla percezione di essere inadeguati.', 'Bordeaux', '#833471', '😳')
on conflict (nome) do update
set
  descrizione = excluded.descrizione,
  colore_assoc = excluded.colore_assoc,
  colore_hex = excluded.colore_hex,
  icona = excluded.icona;
